export default {
    // LOGIN
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    CLEAR_LOGIN: 'CLEAR_LOGIN',

    //REGISTER
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    VERIFY_ACCOUNT_SUCCESS: 'VERIFY_ACCOUNT_SUCCESS',
    VERIFY_ACCOUNT_ERROR: 'VERIFY_ACCOUNT_ERROR',
    CLEAR_REGISTER: 'CLEAR_REGISTER',

    // LOADER
    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',

    // LOADING
    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',


    // PROFILE
    GET_PROFILE: 'GET_PROFILE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',

    // PASSWORD RECOVERY
    SEND_CODE_PASSWORD_RECOVERY_SUCCESS: 'SEND_CODE_PASSWORD_RECOVERY_SUCCESS',
    SEND_CODE_PASSWORD_RECOVERY_ERROR: 'SEND_CODE_PASSWORD_RECOVERY_ERROR',
    PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
    PASSWORD_RESET_ERROR: 'PASSWORD_RESET_ERROR',
    CLEAR_PASSWORD_RECOVERY: 'CLEAR_PASSWORD_RECOVERY',
    SHOW_MODAL: 'SHOW_MODAL',
    HIDE_MODAL: 'HIDE_MODAL',

    //ACTIVATE ACCOUNT
    ACTIVATE_ACCOUNT_SUCCESS: 'ACTIVATE_ACCOUNT_SUCCESS',
    ACTIVATE_ACCOUNT_ERROR: 'ACTIVATE_ACCOUNT_ERROR',
    CLEAR_ACTIVATE_ACCOUNT: 'CLEAR_ACTIVATE_ACCOUNT',
    SEND_CODE_ACTIVATE_ACCOUNT_SUCCESS: 'SEND_CODE_ACTIVATE_ACCOUNT_SUCCESS',
    SEND_CODE_ACTIVATE_ACCOUNT_ERROR: 'SEND_CODE_ACTIVATE_ACCOUNT_ERROR',

};
